[package]
name = "interview_pairing"
version = "0.1.0"
authors = ["David Gregory <david.gregory@opencastsoftware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
